### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by Dark-Peace** [nklbdev/godot-tile-palette#1]
In your readme, the asset library download link isn't working. It redirects you to a page with the id 6540 but your project ID is 1528. The link on your youtube video is working.

**Comment by nklbdev** [comment]
Thank you!

**Comment by nklbdev** [comment]
fixed in commit [update download link closes#1](https://github.com/nklbdev/godot-tile-palette/commit/acc75cd781c04642d9fd1dc90fd6d2548c9024db)
