### ISSUE TITLE
Panning and Multiselection

### ISSUE THREAD

**Issue by letsgamedev** [nklbdev/godot-tile-palette#2]
Hello nklbdev!
We just saw your wonderful plugin!
This is really a relief after several years of the old style of selecting tiles in Godot!

I just have one problem and one feature to request. If you could implement these this plugin would be really a blessing to us.

The Problem:
We using Tilemaps with a base tile size of 16x16 pixels so we have to zoom in but the zooming just "pushes" our tileset out of sight cause we are not able to drag around the tileset in the panel nor is the mouse trackpad (apple mouse) working.
<img width="1017" alt="Bildschirm­foto 2023-01-24 um 21 50 38" src="https://user-images.githubusercontent.com/4989757/214409684-cab94a27-546f-4880-a5ea-302375a96275.png">
<img width="993" alt="Bildschirm­foto 2023-01-24 um 21 50 45" src="https://user-images.githubusercontent.com/4989757/214409692-ffc67db8-e650-4d27-a2a6-02a4e7afc2bb.png">

The second thing is from our Graphics/MapBuilder Guy.
It would be very nice if there would be the possibility to select multiple single tiles at once like with the copy-pasting tool on the map like in these pictures. Probably by dragging with pressed down right mouse button to make a multiselection?
<img width="558" alt="Bildschirm­foto 2023-01-24 um 21 54 01" src="https://user-images.githubusercontent.com/4989757/214410814-adbe1a60-5bd0-445c-b051-dc1f89c1251c.png">
<img width="450" alt="Bildschirm­foto 2023-01-24 um 21 54 07" src="https://user-images.githubusercontent.com/4989757/214410820-72c7bedb-b099-46a1-8dfa-0788cc239a4d.png">

May this is a small motivation for you, if you could do that, we would love to put you in the "special thanks" credits of our game Spindle^^

**Comment by nklbdev** [comment]
Hello, Tom!
Unfortunately, I will no longer develop this plugin.

It hides the native map editor and manages it like a proxy.
This makes it impossible to:
- make multiple selection
- select multiple tiles or pattern
and so on

Take a look at my new project - Enchanced TileMap Editor
https://github.com/nklbdev/godot-enchanced-tile-map-editor
[image: image.png]
It also hides the native editor, but completely suppresses it and works
independently of it.
This opens up every opportunity!
Currently implemented:
- Multiple selection
- Selection "magic wand"
- Pattern drawing
- Flood Fill
- Drawing lines and rectangles
- Copy patterns in text serialized form to the clipboard

You may get console errors when using this plugin. Please send me reports
so I can make the plugin even better! Feel free to write an issue to the
repository
I would be very happy if you share this plugin with someone else, I really
need feedback!

ср, 25 янв. 2023 г. в 01:57, Tom Bleek ***@***.***>:

**Comment by nklbdev** [comment]
Oh, and in Tile Palette plugin you can zoom texture with tiles layout by
mouse scrolling wheel and drag it by middle mouse button. I hope it helps
you to place it at center of the panel

ср, 25 янв. 2023 г. в 01:57, Tom Bleek ***@***.***>:

**Comment by nklbdev** [comment]
Hello, Tom!
Unfortunately, I will no longer develop this plugin.

It hides the native map editor and manages it like a proxy.
This makes it impossible to:
- make multiple selection
- select multiple tiles or pattern
and so on

Take a look at my new project - [Enchanced TileMap Editor](https://github.com/nklbdev/godot-enchanced-tile-map-editor)
![image](https://user-images.githubusercontent.com/7024016/214442952-e9899aba-8ec7-47c7-b1bc-ef5e82edfd3b.png)

It also hides the native editor, but completely suppresses it and works independently of it.
This opens up every opportunity!
Currently implemented:
- Multiple selection
- Selection "magic wand"
- Pattern drawing
- Flood Fill
- Drawing lines and rectangles
- Copy patterns in text serialized form to the clipboard

You may get console errors when using this plugin. Please send me reports so I can make the plugin even better! Feel free to write an issue to the repository
I would be very happy if you share this plugin with someone else, I really need feedback!

Oh, and in Tile Palette plugin you can zoom texture with tiles layout by mouse scrolling wheel and drag it by middle mouse button. I hope it helps you to place it at center of the panel

**Comment by letsgamedev** [comment]
Oh very nice! It works quite well so far!
Is there some kind of road map for that tool?
we will definitely using it and if you want making a lot of suggestions XD

**Comment by letsgamedev** [comment]
"drag it by middle mouse button." My Mouse doesn't have a middle mouse button nor a wheel (Apple Magic mouse)
I guess that applies for almost all MacUsers cause they use the Magic Mouse or a Trackpad.

**Comment by nklbdev** [comment]
Oh! I understand! I just commited support for RMB or Ctrl+LMB for panning texture in panel, please try it out. Not from AssetLibrary but from this repository
81476060136c6fe7e3321e52b68692fef53f8bd7
I requested update asset in Library. It will be updated in 1-2 days
If it works well for you, I will add this feature to the EnchancedTileMapEditor as well.

And if you want, feel free to fork this repository and modify the plugin. I always welcome pull requests!

**Comment by nklbdev** [comment]
@letsgamedev, please write about whether panning works for you now?  so i can close the ticket))

**Comment by letsgamedev** [comment]
yes this works now^^
